version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: batch_example_db
      POSTGRES_USER: batch_example_adm
      POSTGRES_PASSWORD: batch_example_pass