apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # base64 of "root" ($>echo -n "root" | base64)
  db.username: {{ .Values.postgresql.dbUser }}
  db.password: {{ .Values.postgresql.dbPassword }}