namespace: batch

input:
  mount_path: /tmp/input
  filename: customers.csv

bitnami:
  helm:
    repo:
      name: bitnami
      url: https://charts.bitnami.com/bitnami

maven:
  m2_settings_secret_name: m2-settings
  maven_repo_pvc: maven-repo

postgresql:
  helm:
    chart:
      name: postgresql
  port: 5432
  service_name: my-postgresql
  driver_class_name: org.postgresql.Driver
  database: batch_example_db
  username: batch_example_adm
  password: batch_example_pass

