- name: Add bitnami Helm repo
  kubernetes.core.helm_repository:
      name: '{{ postgresql.helm.repo.name }}'
      repo_state: present
      repo_url: '{{ postgresql.helm.repo.url }}'

- name: Install Postgresql Helm Chart
  kubernetes.core.helm:
      # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
      name: '{{ postgresql.service_name }}'
      namespace: '{{ namespace }}'
      chart_ref: '{{ postgresql.helm.repo.name }}/{{ postgresql.helm.chart.name }}'
      wait: true
      values:
        auth:
          database: '{{ postgresql.database }}'
          username: '{{ postgresql.username }}'
          password: '{{ postgresql.password }}'

- name: Expose Postgresql port
  shell: >
    nohup kubectl port-forward svc/{{ postgresql.service_name }} {{ postgresql.port }}:{{ postgresql.port }}  --address='0.0.0.0' --namespace {{ namespace }} >/dev/null 2>&1 &