- name: Add Spring Boot Batch Helm repo
  kubernetes.core.helm_repository:
      name: '{{ batch.helm.repo.name }}'
      repo_state: present
      force_update: true
      repo_url: '{{ batch.helm.repo.url }}'

- name: Install Spring Boot Batch Chart
  kubernetes.core.helm:
      name: github
      namespace: '{{ namespace }}'
      chart_ref: '{{ batch.helm.repo.name }}/{{ batch.helm.chart.name }}'
      chart_version: '{{ batch.helm.chart.version }}'
      wait: true
      values:
        jobVersion: '{{ ansible_date_time.epoch }}'
        image:
          tag: '{{ batch.image.tag }}'
        postgresql:
          serviceName: '{{ postgresql.service_name }}'
          port: '{{ postgresql.port }}'
          dbName: '{{ postgresql.database }}'
          dbUser: '{{ postgresql.username }}'
          dbPassword: '{{ postgresql.password }}'
