- name: Add Spring Boot Batch Helm repo
  kubernetes.core.helm_repository:
      name: spring-boot-batch
      repo_url: https://raw.githubusercontent.com/erwanjouan/spring-boot-batch/gh-pages/

- name: Install Spring Boot Batch Chart
  kubernetes.core.helm:
      name: spring-boot-batch
      namespace: '{{ namespace }}'
      chart_ref: spring-boot-batch
      wait: true
