- name: Add Spring Boot Batch Helm repo
  kubernetes.core.helm_repository:
      name: github
      force_update: true
      repo_url: https://raw.githubusercontent.com/erwanjouan/spring-boot-batch/gh-pages/

- name: Install Spring Boot Batch Chart
  kubernetes.core.helm:
      name: github
      namespace: '{{ namespace }}'
      chart_ref: github/spring-batch-job
      chart_version: 0.1.6
      wait: true
      values:
        jobVersion: '{{ ansible_date_time.epoch }}'
        postgresql:
          serviceName: '{{ postgresql.service_name }}'
          port: '{{ postgresql.port }}'
          dbName: '{{ postgresql.database }}'
          dbUser: '{{ postgresql.username }}'
          dbPassword: '{{ postgresql.password }}'
